# {"event"=>"TASK.CREATED", "objectId"=>"2149552", "accountId"=>"220732", "userId"=>"63741", "splat"=>["/api/teamwork/task-created"], "captures"=>["/api/teamwork/task-created"]}
{
  "CALENDAREVENT.CREATED" : "" },
  "CALENDAREVENT.DELETED" : "" },
  "CALENDAREVENT.UPDATED" : "" },
  "COMMENT.CREATED" :       "" },
  "COMMENT.DELETED" :       "" },
  "COMMENT.UPDATED" :       "" },
  "COMPANY.CREATED" :       "" },
  "COMPANY.DELETED" :       "" },
  "COMPANY.UPDATED" :       "" },
  "FILE.CREATED" :          "" },
  "FILE.DELETED" :          "" },
  "FILE.DOWNLOADED" :       "" },
  "FILE.UPDATED" :          "" },
  "LINK.CREATED" :          "" },
  "LINK.DELETED" :          "" },
  "LINK.UPDATED" :          "" },
  "MESSAGE.CREATED" :       "" },
  "MESSAGE.DELETED" :       "" },
  "MESSAGE.UPDATED" :       "" },
  "MESSAGEREPLY.CREATED" :  "" },
  "MESSAGEREPLY.DELETED" :  "" },
  "MESSAGEREPLY.UPDATED" :  "" },
  "MILESTONE.COMPLETED" :   "" },
  "MILESTONE.CREATED" :     "" },
  "MILESTONE.DELETED" :     "" },
  "MILESTONE.REOPENED" :    "" },
  "MILESTONE.UPDATED" :     "" },
  "NOTEBOOK.CREATED" :      "" },
  "NOTEBOOK.DELETED" :      "" },
  "NOTEBOOK.UPDATED" :      "" },
  "PROJECT.CREATED":        "" },
  "PROJECT.ARCHIVED" :      "" },
  "PROJECT.DELETED" :       "" },
  "PROJECT.REOPENED" :      "" },
  "PROJECT.UPDATED" :       "" },
  "STATUS.CREATED" :        "" },
  "STATUS.DELETED" :        "" },
  "STATUS.UPDATED" :        "" },
  "TASK.COMPLETED" :        "" },
  "TASK.CREATED":           "" },
  "TASK.DELETED" :          "" },
  "TASK.REOPENED" :         "" },
  "TASK.UPDATED" :          "" },
  "TASKLIST.CREATED":       "" },
  "TASKLIST.COMPLETED" :    "" },
  "TASKLIST.DELETED" :      "" },
  "TASKLIST.REOPENED" :     "" },
  "TASKLIST.UPDATED" :      "" },
  "TIME.CREATED" :          "" },
  "TIME.DELETED" :          "" },
  "TIME.UPDATED" :          "" },
  "USER.CREATED" :          "" },
  "USER.DELETED" :          "" },
  "USER.UPDATED" :          "" }
}
